version: '3.8'

services:
  jenkins:
    build: ./jenkins
    user: jenkins
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data:/var/jenkins_home
      - /home/ubuntu/S12P11B105/nginx/conf.d:/etc/nginx/conf.d  # 호스트의 conf.d 디렉토리를 Jenkins 컨테이너에 마운트
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    privileged: true

volumes:
  jenkins_home: