# nginx/nginx.conf
events {}

http {
    server {
        listen 80;
        server_name i12b105.p.ssafy.io;  # 도메인으로 변경

        location / {
            return 301 https://$host$request_uri;  # HTTP를 HTTPS로 리다이렉트
        }
    }

    server {
        listen 443 ssl;
        server_name i12b105.p.ssafy.io;  # 도메인으로 변경

        ssl_certificate /etc/letsencrypt/live/i12b105.p.ssafy.io/fullchain.pem;  # SSL 인증서 경로
        ssl_certificate_key /etc/letsencrypt/live/i12b105.p.ssafy.io/privkey.pem;  # SSL 키 경로

        location / {
            proxy_pass http://i12b105.p.ssafy.io:3000;  # frontend 서비스로 프록시
        }

        location /api/ {
            proxy_pass http://backend:8080;  # backend 서비스로 프록시
        }
    }
}