events {}


http {
    # 기존 include 설정 유지
    include /etc/nginx/conf.d/*.conf;

    # 헤더 버퍼 크기 설정 추가
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_max_temp_file_size 0;
    
    # 클라이언트 헤더 버퍼 크기 설정 추가
    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;
}