server {
    listen 80;
    server_name i12b105.p.ssafy.io;

    location / {
        proxy_pass http://frontend:3000;  # 프론트엔드 서비스로 프록시
    }

    location /api/ {
        proxy_pass http://backend:8080;  # 백엔드 서비스로 프록시
    }
}