server {
    listen 80;
    server_name i12b105.p.ssafy.io;

    # HTTP 요청을 HTTPS로 리디렉션
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name i12b105.p.ssafy.io;

    # 기존에는 호스트머신 기준
    # ssl_certificate /etc/letsencrypt/live/i12b105.p.ssafy.io/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/i12b105.p.ssafy.io/privkey.pem;

    # Jenkins 기준  ( 왜냐면 pem 값들 젠킨스 컨테이너 내부로 복사함)
    ssl_certificate /var/jenkins_home/certs/fullchain.pem;
    ssl_certificate_key /var/jenkins_home/certs/privkey.pem;


    location / {
        proxy_pass http://frontend:3000;  # 프론트엔드 서비스로 프록시
    }

    location /api/ {
        proxy_pass http://backend:8080;  # 백엔드 서비스로 프록시
    }
}