version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    env_file:
      - /var/jenkins_home/workspace/jenkinsTest/jenkins/.env  # Jenkins 컨테이너 내부 절대 경로


  
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ssafyalbaro105
      MYSQL_DATABASE: albaro
      MYSQL_USER: albaro
      MYSQL_PASSWORD: ssafyalbaro105
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/albaro?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=albaro
      - SPRING_DATASOURCE_PASSWORD=ssafyalbaro105
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app.jar"]



  nginx:
  build: ../nginx
  ports:
    - "80:80"
    - "443:443"  # HTTPS 포트 추가
  volumes:
    - ../nginx/conf.d:/etc/nginx/conf.d
    - /etc/letsencrypt/live/i12b105.p.ssafy.io:/etc/letsencrypt/live/i12b105.p.ssafy.io  # 호스트의 인증서 경로를 컨테이너에 마운트
  depends_on:
    - frontend
    - backend
    

  certbot:
    image: certbot/certbot
    volumes:
      - ../nginx/certs:/etc/letsencrypt
      - ../nginx/conf.d:/etc/nginx/conf.d
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  face_recognition:
    build:
      context: ../face_recognition  
    ports:
      - "5000:5000"  
    depends_on:
      - backend  

volumes:
  db_data: