pipeline {
    agent any

    environment {
        EC2_IP = 'i12b105.p.ssafy.io'
        SSH_KEY = 'C:/Users/SSAFY/Desktop/I12B105T.pem'
        PROJECT_PATH = '/var/jenkins_home/workspace/jenkinsTest/jenkins'  // Jenkins 컨테이너 내부 절대 경로
        GIT_REPO_URL = 'https://lab.ssafy.com/s12-webmobile1-sub1/S12P11B105.git'
        GIT_BRANCH = 'develop'
        DOCKER_COMPOSE_PATH = '/usr/local/bin/docker-compose'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${GIT_REPO_URL}", branch: "${GIT_BRANCH}", credentialsId: 'Gitlab'
            }
        }

        stage('.env 파일 생성') {
            steps {
                withCredentials([string(credentialsId: 'NEXT_PUBLIC_KAKAO_KEY', variable: 'NEXT_PUBLIC_KAKAO_KEY')]) {
                    script {
                        sh '''
                        mkdir -p $PROJECT_PATH
                        echo "NEXT_PUBLIC_KAKAO_KEY=$NEXT_PUBLIC_KAKAO_KEY" > $PROJECT_PATH/.env
                        cp $PROJECT_PATH/.env /var/jenkins_home/workspace/jenkinsTest/frontend/.env  // 정확한 경로로 복사
                        '''
                    }
                }
            }
        }

        stage('기존 컨테이너 중지 및 제거') {
            steps {
                script {
                    sh '''
                    cd $PROJECT_PATH
                    $DOCKER_COMPOSE_PATH down
                    '''
                }
            }
        }

        stage('컨테이너 빌드 및 시작') {
            steps {
                script {
                    sh '''
                    cd $PROJECT_PATH
                    $DOCKER_COMPOSE_PATH up --build -d
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '빌드 및 배포가 성공적으로 완료되었습니다! :)'
        }
        failure {
            echo '빌드 또는 배포에 실패했습니다!  ㅡ.ㅡ'
        }
    }
}