pipeline {
    agent any

    environment {
        EC2_IP = 'i12b105.p.ssafy.io'
        SSH_KEY = 'C:/Users/SSAFY/Desktop/I12B105T.pem'
        PROJECT_PATH = "${WORKSPACE}"
        GIT_REPO_URL = 'https://lab.ssafy.com/s12-webmobile1-sub1/S12P11B105.git'
        GIT_BRANCH = 'develop'
        DOCKER_COMPOSE_PATH = '/usr/local/bin/docker-compose'
        NEXT_PUBLIC_KAKAO_KEY = credentials('NEXT_PUBLIC_KAKAO_KEY')
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${GIT_REPO_URL}", branch: "${GIT_BRANCH}", credentialsId: 'Gitlab'
            }
        }

        stage('Create .env file') {
            steps {
                withCredentials([string(credentialsId: 'NEXT_PUBLIC_KAKAO_KEY', variable: 'NEXT_PUBLIC_KAKAO_KEY')]) {
                    script {
                        sh '''
                        echo "NEXT_PUBLIC_KAKAO_KEY=$NEXT_PUBLIC_KAKAO_KEY" > ${PROJECT_PATH}/.env
                        '''
                    }
                }
            }
        }


        stage('Stop and Remove Existing Containers') {
            steps {
                script {
                    // Jenkins 컨테이너 내부에서 도커 컴포즈를 사용하여 기존 컨테이너 중지 및 제거
                    sh '''
                    cd jenkins
                    /usr/local/bin/docker-compose down
                    '''
                }
            }
        }

        stage('Build and Start Containers') {
            steps {
                script {
                    // Jenkins 컨테이너 내부에서 도커 컴포즈 실행
                    sh '''
                    cd jenkins
                    /usr/local/bin/docker-compose up --build -d
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '빌드 및 배포가 성공적으로 완료되었습니다! :)'
        }
        failure {
            echo '빌드 또는 배포에 실패했습니다!  ㅡ.ㅡ'
        }
    }
}